"use strict";
/**
 * @fileoverview gRPC-Web generated client stub for helloworld
 * @enhanceable
 * @public
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GreeterClient = void 0;
// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: protos/helloworld/helloworld_service.proto
/* eslint-disable */
// @ts-nocheck
var grpcWeb = __importStar(require("grpc-web"));
var protos_helloworld_helloworld_pb = __importStar(require("../../protos/helloworld/helloworld_pb")); // proto import: "protos/helloworld/helloworld.proto"
var GreeterClient = /** @class */ (function () {
    function GreeterClient(hostname, credentials, options) {
        this.methodDescriptorSayHello = new grpcWeb.MethodDescriptor('/helloworld.Greeter/SayHello', grpcWeb.MethodType.UNARY, protos_helloworld_helloworld_pb.HelloRequest, protos_helloworld_helloworld_pb.HelloReply, function (request) {
            return request.serializeBinary();
        }, protos_helloworld_helloworld_pb.HelloReply.deserializeBinary);
        if (!options)
            options = {};
        if (!credentials)
            credentials = {};
        options['format'] = 'binary';
        this.client_ = new grpcWeb.GrpcWebClientBase(options);
        this.hostname_ = hostname.replace(/\/+$/, '');
        this.credentials_ = credentials;
        this.options_ = options;
    }
    GreeterClient.prototype.sayHello = function (request, metadata, callback) {
        if (callback !== undefined) {
            return this.client_.rpcCall(this.hostname_ +
                '/helloworld.Greeter/SayHello', request, metadata || {}, this.methodDescriptorSayHello, callback);
        }
        return this.client_.unaryCall(this.hostname_ +
            '/helloworld.Greeter/SayHello', request, metadata || {}, this.methodDescriptorSayHello);
    };
    return GreeterClient;
}());
exports.GreeterClient = GreeterClient;
