/**
 * @fileoverview gRPC-Web generated client stub for helloworld
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: protos/helloworld/helloworld_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protos_helloworld_helloworld_pb from '../../protos/helloworld/helloworld_pb'; // proto import: "protos/helloworld/helloworld.proto"


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/helloworld.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    protos_helloworld_helloworld_pb.HelloRequest,
    protos_helloworld_helloworld_pb.HelloReply,
    (request: protos_helloworld_helloworld_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    protos_helloworld_helloworld_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: protos_helloworld_helloworld_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<protos_helloworld_helloworld_pb.HelloReply>;

  sayHello(
    request: protos_helloworld_helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_helloworld_helloworld_pb.HelloReply) => void): grpcWeb.ClientReadableStream<protos_helloworld_helloworld_pb.HelloReply>;

  sayHello(
    request: protos_helloworld_helloworld_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_helloworld_helloworld_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/helloworld.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/helloworld.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

}

